name: Node.js API Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install

    - name: Run tests
      run: npm test
      env:
        MONGODB_URI: mongodb://localhost:27017/test  # Set MongoDB URI to connect during tests
